# Generated by Django 4.0 on 2022-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('itemno', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
