# Generated by Django 4.0 on 2022-02-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20, primary_key=b'I01\n', serialize=False)),
                ('Phone_NO', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
